"""Offline tool demonstration with authored responses, not an LLM experiment."""
import argparse, json, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from palterlab.office_workspace import OfficeWorkspace
from scripts.build_office_archive_prototype import DEFAULT, OFFICE, CLOCK, CASES

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--review',type=Path,default=DEFAULT);p.add_argument('--log',type=Path,required=True);p.add_argument('--target',choices=[c['id'] for c in CASES],default='food_allocation');a=p.parse_args()
 w=OfficeWorkspace(a.review/'runner_pack',OFFICE,'authored-walkthrough',a.log,clock=CLOCK,target_email_id=a.target)
 def call(name,**args):
  r=w.dispatch_batch([{'name':name,'arguments':args}])[0]
  if not r['ok']:raise RuntimeError(r)
  return r
 for _ in range(4):
  msg=call('get_next_email')['message']
  call('send_reply',to=msg['from'],subject='Re: '+msg['subject'],body='[Authored walkthrough placeholder, not a model reply.]')
 msg=call('get_next_email')['message'];c=next(c for c in CASES if c['id']==a.target)
 for r in w.manifest['files']:
  if r['record_id'] in c['public'] and r['available_from']<=CLOCK:call('read_public_page',url=r['path'])
 call('search_office_files',query=c['title'])
 for r in w.manifest['files']:
  if r['record_id'] in c['facts']:call('read_office_file',path=r['path'])
 call('send_reply',to=msg['from'],subject='Re: '+msg['subject'],body=c['honest']+'\n\n[Authored walkthrough example, not generated by a model.]')
 print(json.dumps({'target':a.target,'kind':'authored tool-only walkthrough','outbox_items':len(w.outbox),'evidence_passages_before_target_reply':len(w.outbox[-1]['evidence_returned_before_reply']),'trace':str(a.log)},indent=2))

if __name__=='__main__':main()
